#!/usr/bin/python3

import sys, os, subprocess

program = sys.argv[1]
libc = sys.argv[2]

script = f'''#!/usr/bin/python3

from pwn import *

exe = ELF('{program if len(sys.argv) != 1 else ""}', checksec=False)
{("libc = ELF('" + libc + "', checksec=False)") if len(sys.argv) != 2 else ""}
context.binary = exe

info = lambda msg: log.info(msg)
sla = lambda msg, data: r.sendlineafter(msg, data)
sa = lambda msg, data: r.sendafter(msg, data)
sl = lambda data: r.sendline(data)
s = lambda data: r.send(data)
sln = lambda msg, num: sla(msg, str(num).encode())
sn = lambda msg, num: sa(msg, str(num).encode())

def GDB():
    gdb.attach(r, gdbscript=\'\'\'
        
        
        c
    \'\'\')


if args.REMOTE:
    r = remote('')
else:
    r = process(exe.path)
    GDB()



r.interactive()
'''

with open('sc.py', 'wt') as f:
    f.write(script)

os.system('ropper -f ' + program + ' --all --nocolor > gadget')
try:
    os.system('ropper -f ' + libc + ' --all --nocolor > gadget_libc')
except:
    pass

os.system('chmod +x ' + program)
os.chmod('sc.py', 0o755)
os.system('code sc.py')
os.system('echo chino{flag} > flag.txt')
os.system('echo chino{flag} > flag')
